"""add scheduled metrics

Revision ID: ed73250b7656
Revises: 7f4bbec1b669
Create Date: 2023-04-27 10:26:09.071536

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ed73250b7656"
down_revision = "7f4bbec1b669"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "static_stop_times",
        sa.Column("schedule_travel_time_seconds", sa.Integer(), nullable=True),
    )
    op.add_column(
        "static_stop_times",
        sa.Column(
            "schedule_headway_trunk_seconds", sa.Integer(), nullable=True
        ),
    )
    op.add_column(
        "static_stop_times",
        sa.Column(
            "schedule_headway_branch_seconds", sa.Integer(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("static_stop_times", "schedule_headway_branch_seconds")
    op.drop_column("static_stop_times", "schedule_headway_trunk_seconds")
    op.drop_column("static_stop_times", "schedule_travel_time_seconds")
    # ### end Alembic commands ###
