"""fix trip_id length

Revision ID: e2399b814cd7
Revises: 37d97f420d54
Create Date: 2023-11-27 10:56:33.320324

Details:
* upgrade -> change "trip_id" field from lenth 128 to 512
* upgrade -> fix database state for static_version_key = 1700702558

* downgrade -> change "trip_id" field from lenth 512 to 128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2399b814cd7"
down_revision = "37d97f420d54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS opmi_all_rt_fields_joined;")

    op.execute("ALTER TABLE vehicle_trips DROP CONSTRAINT vehicle_trips_static_version_key_fkey;")

    static_tables = (
        "static_trips",
        "static_routes",
        "static_stops",
        "static_stop_times",
        "static_calendar",
        "static_calendar_dates",
        "static_directions",
        "static_feed_info",
    )

    for table in static_tables:
        clean_static = f"""
            DELETE 
            FROM {table} 
            WHERE static_version_key = 1700702558 
            ;
        """
        op.execute(clean_static)

    op.alter_column(
        "static_stop_times",
        "trip_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "static_trips",
        "trip_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "vehicle_trips",
        "trip_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=512),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicle_trips",
        "static_trip_id_guess",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=512),
        existing_nullable=True,
    )

    update_medata_log = """
        UPDATE metadata_log 
        SET processed = false, process_fail = false
        WHERE pk_id = 64788
        ;
    """
    op.execute(update_medata_log)

    re_create_view = """
        CREATE OR REPLACE VIEW opmi_all_rt_fields_joined AS 
        SELECT
            vt.service_date
            , ve.trip_hash
            , ve.trip_stop_hash
            , ve.stop_sequence
            , ve.stop_id
            , LAG (ve.stop_id, 1) OVER (PARTITION BY ve.trip_hash ORDER BY COALESCE(ve.vp_stop_timestamp,  ve.tu_stop_timestamp, ve.vp_move_timestamp)) as previous_stop_id
            , ve.parent_station
            , LAG (ve.parent_station, 1) OVER (PARTITION BY ve.trip_hash ORDER BY COALESCE(ve.vp_stop_timestamp,  ve.tu_stop_timestamp, ve.vp_move_timestamp)) as previous_parent_station
            , ve.vp_move_timestamp
            , COALESCE(ve.vp_stop_timestamp,  ve.tu_stop_timestamp) as vp_tu_stop_timestamp
            , vt.direction_id
            , vt.route_id
            , vt.branch_route_id
            , vt.trunk_route_id
            , vt.start_time
            , vt.vehicle_id
            , vt.stop_count
            , vt.trip_id
            , vt.vehicle_label
            , vt.vehicle_consist
            , vt.direction
            , vt.direction_destination
            , vt.static_trip_id_guess
            , vt.static_start_time
            , vt.static_stop_count
            , vt.first_last_station_match
            , vt.static_version_key
            , vem.travel_time_seconds
            , vem.dwell_time_seconds
            , vem.headway_trunk_seconds
            , vem.headway_branch_seconds
            , COALESCE(vem.updated_on, ve.updated_on) as updated_on
        FROM 
            vehicle_events ve
        LEFT JOIN
            vehicle_trips vt
        ON 
            ve.trip_hash = vt.trip_hash
        LEFT JOIN 
            vehicle_event_metrics vem
        ON
            ve.trip_stop_hash = vem.trip_stop_hash
        ;
    """
    op.execute(re_create_view)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS opmi_all_rt_fields_joined;")
    op.alter_column(
        "vehicle_trips",
        "static_trip_id_guess",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicle_trips",
        "trip_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "static_trips",
        "trip_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "static_stop_times",
        "trip_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    re_create_view = """
        CREATE OR REPLACE VIEW opmi_all_rt_fields_joined AS 
        SELECT
            vt.service_date
            , ve.trip_hash
            , ve.trip_stop_hash
            , ve.stop_sequence
            , ve.stop_id
            , LAG (ve.stop_id, 1) OVER (PARTITION BY ve.trip_hash ORDER BY COALESCE(ve.vp_stop_timestamp,  ve.tu_stop_timestamp, ve.vp_move_timestamp)) as previous_stop_id
            , ve.parent_station
            , LAG (ve.parent_station, 1) OVER (PARTITION BY ve.trip_hash ORDER BY COALESCE(ve.vp_stop_timestamp,  ve.tu_stop_timestamp, ve.vp_move_timestamp)) as previous_parent_station
            , ve.vp_move_timestamp
            , COALESCE(ve.vp_stop_timestamp,  ve.tu_stop_timestamp) as vp_tu_stop_timestamp
            , vt.direction_id
            , vt.route_id
            , vt.branch_route_id
            , vt.trunk_route_id
            , vt.start_time
            , vt.vehicle_id
            , vt.stop_count
            , vt.trip_id
            , vt.vehicle_label
            , vt.vehicle_consist
            , vt.direction
            , vt.direction_destination
            , vt.static_trip_id_guess
            , vt.static_start_time
            , vt.static_stop_count
            , vt.first_last_station_match
            , vt.static_version_key
            , vem.travel_time_seconds
            , vem.dwell_time_seconds
            , vem.headway_trunk_seconds
            , vem.headway_branch_seconds
            , COALESCE(vem.updated_on, ve.updated_on) as updated_on
        FROM 
            vehicle_events ve
        LEFT JOIN
            vehicle_trips vt
        ON 
            ve.trip_hash = vt.trip_hash
        LEFT JOIN 
            vehicle_event_metrics vem
        ON
            ve.trip_stop_hash = vem.trip_stop_hash
        ;
    """
    op.execute(re_create_view)
    # ### end Alembic commands ###
