"""add vehicle info to trips

Revision ID: 9d3515f1386e
Revises: 695ef31623ae
Create Date: 2023-05-08 14:48:07.237537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d3515f1386e"
down_revision = "695ef31623ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "static_trips",
        sa.Column("block_id", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "vehicle_trips",
        sa.Column("vehicle_label", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "vehicle_trips",
        sa.Column(
            "vehicle_consist",
            sa.String(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_trips", "vehicle_consist")
    op.drop_column("vehicle_trips", "vehicle_label")
    op.drop_column("static_trips", "block_id")
    # ### end Alembic commands ###
