"""fix slow static schedule loading

Revision ID: de55dc40315d
Revises: 001aa247c451
Create Date: 2023-05-03 05:58:04.607402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de55dc40315d"
down_revision = "001aa247c451"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_static_stop_times_timestamp"),
        "static_stop_times",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_stop_times_stop_id"),
        "static_stop_times",
        ["stop_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_stop_times_trip_id"),
        "static_stop_times",
        ["trip_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_stops_stop_id"),
        "static_stops",
        ["stop_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_stops_timestamp"),
        "static_stops",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_trips_service_id"),
        "static_trips",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_trips_direction_id"),
        "static_trips",
        ["direction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_trips_timestamp"),
        "static_trips",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_static_trips_trip_id"),
        "static_trips",
        ["trip_id"],
        unique=False,
    )
    op.create_table(
        "temp_static_headways_gen",
        sa.Column("pk_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("departure_time", sa.Integer(), nullable=False),
        sa.Column("parent_station", sa.String(length=30), nullable=False),
        sa.Column("service_id", sa.String(length=60), nullable=False),
        sa.Column("direction_id", sa.Boolean(), nullable=True),
        sa.Column("trunk_route_id", sa.String(length=60), nullable=True),
        sa.Column("branch_route_id", sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint("pk_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temp_static_headways_gen")
    op.drop_index(op.f("ix_static_trips_trip_id"), table_name="static_trips")
    op.drop_index(op.f("ix_static_trips_timestamp"), table_name="static_trips")
    op.drop_index(
        op.f("ix_static_trips_direction_id"), table_name="static_trips"
    )
    op.drop_index(op.f("ix_static_trips_service_id"), table_name="static_trips")
    op.drop_index(op.f("ix_static_stops_timestamp"), table_name="static_stops")
    op.drop_index(op.f("ix_static_stops_stop_id"), table_name="static_stops")
    op.drop_index(
        op.f("ix_static_stop_times_trip_id"), table_name="static_stop_times"
    )
    op.drop_index(
        op.f("ix_static_stop_times_stop_id"), table_name="static_stop_times"
    )
    op.drop_index(
        op.f("ix_static_stop_times_timestamp"), table_name="static_stop_times"
    )
    # ### end Alembic commands ###
