from typing import List, Tuple
import dataframely as dy
import pyarrow

from lamp_py.ingestion.gtfs_rt_detail import GTFSRTDetail, FeedMessage, FeedEntityTable
from lamp_py.ingestion.gtfs_rt_structs import (
    position,
    trip_descriptor,
    vehicle_descriptor,
)
from lamp_py.utils.dataframely import with_nullable


class VehicleRecord(FeedMessage):
    """Each VehiclePosition message generated by GTFS-RT."""

    entity = dy.List(
        inner=dy.Struct(
            inner={
                "id": dy.String(min_length=1),
                "vehicle": dy.Struct(
                    inner={
                        "trip": trip_descriptor,
                        "vehicle": vehicle_descriptor,
                        "position": with_nullable(position, nullable=True),
                        "current_stop_sequence": dy.UInt32(nullable=True),
                        "stop_id": dy.String(nullable=True),
                        "current_status": dy.String(nullable=True),
                        "timestamp": dy.UInt64(nullable=True),
                        "congestion_level": dy.String(nullable=True),
                        "occupancy_status": dy.String(nullable=True),
                        "occupancy_percentage": dy.UInt32(nullable=True),
                        "multi_carriage_details": dy.List(
                            dy.Struct(
                                inner={
                                    "id": dy.String(nullable=True),
                                    "label": dy.String(nullable=True),
                                    "occupancy_status": dy.String(nullable=True),
                                    "occupancy_percentage": dy.Int32(nullable=True),
                                    "carriage_sequence": dy.UInt32(nullable=True),
                                }
                            ),
                            nullable=True,
                        ),
                    }
                ),
            }
        ),
        min_length=1,
    )


class VehicleTable(FeedEntityTable):
    """Flattened GTFS-RT VehiclePositions data."""

    position_bearing = dy.UInt16(nullable=True, alias="vehicle.position.bearing")
    position_latitude = dy.Float64(nullable=True, alias="vehicle.position.latitude")
    position_longitude = dy.Float64(nullable=True, alias="vehicle.position.longitude")
    position_speed = dy.Float64(nullable=True, alias="vehicle.position.speed")
    position_odometer = dy.Float64(nullable=True, alias="vehicle.position.odometer")
    trip_id = dy.String(nullable=True, alias="vehicle.trip.trip_id")
    route_id = dy.String(nullable=True, alias="vehicle.trip.route_id")
    direction_id = dy.UInt8(nullable=True, alias="vehicle.trip.direction_id")
    trip_start_time = dy.String(nullable=True, alias="vehicle.trip.start_time")
    trip_start_date = dy.String(nullable=True, alias="vehicle.trip.start_date")
    trip_schedule_relationship = dy.String(nullable=True, alias="vehicle.trip.schedule_relationship")
    vehicle_id = dy.String(nullable=True, alias="vehicle.vehicle.id")
    vehicle_label = dy.String(nullable=True, alias="vehicle.vehicle.label")
    vehicle_license_plate = dy.String(nullable=True, alias="vehicle.vehicle.license_plate")
    current_stop_sequence = dy.UInt32(nullable=True, alias="vehicle.current_stop_sequence")
    stop_id = dy.String(nullable=True, alias="vehicle.stop_id")
    current_status = dy.String(nullable=True, alias="vehicle.current_status")
    vehicle_timestamp = dy.UInt64(nullable=True, alias="vehicle.timestamp")
    congestion_level = dy.String(nullable=True, alias="vehicle.congestion_level")
    occupancy_status = dy.String(nullable=True, alias="vehicle.occupancy_status")
    occupancy_percentage = dy.UInt32(nullable=True, alias="vehicle.occupancy_percentage")
    multi_carriage_details = dy.List(
        dy.Struct(
            inner={
                "id": dy.String(nullable=True),
                "label": dy.String(nullable=True),
                "occupancy_status": dy.String(nullable=True),
                "occupancy_percentage": dy.Int32(nullable=True),
                "carriage_sequence": dy.UInt32(nullable=True),
            }
        ),
        nullable=True,
        alias="vehicle.multi_carriage_details",
    )


class RtVehicleDetail(GTFSRTDetail[VehicleTable, VehicleRecord]):
    """
    Detail for how to convert RT GTFS Vehicle Positions from json entries into
    parquet tables.
    """

    @property
    def table_schema(self) -> type[VehicleTable]:
        return VehicleTable

    @property
    def record_schema(self) -> type[VehicleRecord]:
        return VehicleRecord

    @property
    def partition_column(self) -> str:
        return "vehicle.trip.route_id"

    @property
    def import_schema(self) -> pyarrow.schema:
        return pyarrow.schema([v.pyarrow_field(k) for k, v in self.record_schema.entity.inner.inner.items()])  # type: ignore[attr-defined]

    @property
    def table_sort_order(self) -> List[Tuple[str, str]]:
        return [
            ("vehicle.vehicle.id", "ascending"),
            ("vehicle.trip.direction_id", "ascending"),
        ]
