from typing import List, Tuple
import dataframely as dy
import pyarrow

from .gtfs_rt_detail import GTFSRTDetail
from .gtfs_rt_structs import (
    position,
    vehicle_descriptor,
    trip_descriptor,
)


class BusLocVehicleRecord(dy.Schema):
    """Each VehiclePosition message generated by BusLoc."""

    header = dy.Struct(
        inner={
            "gtfs_realtime_version": dy.String(),
            "incrementality": dy.String(),
            "timestamp": dy.UInt64(),
        }
    )
    entity = dy.List(
        inner=dy.Struct(
            inner={
                "id": dy.String(min_length=1),
                "is_deleted": dy.Bool(),
                "vehicle": dy.Struct(
                    inner={
                        "position": position,
                        "location_source": dy.String(nullable=True),
                        "timestamp": dy.UInt64(nullable=True),
                        "trip": trip_descriptor,
                        "vehicle": vehicle_descriptor,
                        "operator": dy.Struct(
                            inner={
                                "id": dy.String(nullable=True),
                                "first_name": dy.String(metadata={"reader_roles": ["OperatorName"]}, nullable=True),
                                "last_name": dy.String(metadata={"reader_roles": ["OperatorName"]}, nullable=True),
                                "name": dy.String(metadata={"reader_roles": ["OperatorName"]}, nullable=True),
                                "logon_time": dy.UInt64(nullable=True),
                            },
                            nullable=True,
                        ),
                        "block_id": dy.String(nullable=True),
                        "run_id": dy.String(nullable=True),
                        "stop_id": dy.String(nullable=True),
                        "current_stop_sequence": dy.UInt32(nullable=True),
                        "revenue": dy.Bool(nullable=True),
                        "current_status": dy.String(nullable=True),
                        "load": dy.UInt16(nullable=True),
                        "capacity": dy.UInt16(nullable=True),
                        "occupancy_percentage": dy.UInt16(nullable=True),
                        "occupancy_status": dy.String(nullable=True),
                        "state_of_charge_percentage": dy.UInt16(nullable=True),
                        "state_of_charge_timestamp": dy.UInt64(nullable=True),
                    }
                ),
            }
        ),
        min_length=1,
    )


class BusLocVehicleTable(dy.Schema):
    """Flattened BusLoc VehiclePositions data."""

    id = dy.String(primary_key=True)
    feed_timestamp = dy.UInt64(primary_key=True)
    is_deleted = dy.Bool(nullable=True)
    position_bearing = dy.UInt16(nullable=True, alias="vehicle.position.bearing")
    position_latitude = dy.Float64(nullable=True, alias="vehicle.position.latitude")
    position_longitude = dy.Float64(nullable=True, alias="vehicle.position.longitude")
    position_speed = dy.Float64(nullable=True, alias="vehicle.position.speed")
    position_odometer = dy.Float64(nullable=True, alias="vehicle.position.odometer")
    location_source = dy.String(nullable=True, alias="vehicle.location_source")
    vehicle_timestamp = dy.UInt64(nullable=True, alias="vehicle.timestamp")
    trip_id = dy.String(nullable=True, alias="vehicle.trip.trip_id")
    route_id = dy.String(nullable=True, alias="vehicle.trip.route_id")
    direction_id = dy.UInt8(nullable=True, alias="vehicle.trip.direction_id")
    trip_start_time = dy.String(nullable=True, alias="vehicle.trip.start_time")
    trip_start_date = dy.String(nullable=True, alias="vehicle.trip.start_date")
    trip_schedule_relationship = dy.String(nullable=True, alias="vehicle.trip.schedule_relationship")
    trip_route_pattern_id = dy.String(nullable=True, alias="vehicle.trip.route_pattern_id")
    trip_tm_trip_id = dy.String(nullable=True, alias="vehicle.trip.tm_trip_id")
    trip_overload_id = dy.Int64(nullable=True, alias="vehicle.trip.overload_id")
    trip_overload_offset = dy.Int64(nullable=True, alias="vehicle.trip.overload_offset")
    trip_revenue = dy.Bool(nullable=True, alias="vehicle.trip.revenue")
    trip_last_trip = dy.Bool(nullable=True, alias="vehicle.trip.last_trip")
    vehicle_id = dy.String(nullable=True, alias="vehicle.vehicle.id")
    vehicle_label = dy.String(nullable=True, alias="vehicle.vehicle.label")
    vehicle_license_plate = dy.String(nullable=True, alias="vehicle.vehicle.license_plate")
    vehicle_consist = dy.List(
        dy.Struct(inner={"label": dy.String(nullable=True)}), nullable=True, alias="vehicle.vehicle.consist"
    )
    vehicle_assignment_status = dy.String(nullable=True, alias="vehicle.vehicle.assignment_status")
    operator_id = dy.String(nullable=True, alias="vehicle.operator.id")
    operator_first_name = dy.String(
        metadata={"reader_roles": ["OperatorName"]}, nullable=True, alias="vehicle.operator.first_name"
    )
    operator_last_name = dy.String(
        metadata={"reader_roles": ["OperatorName"]}, nullable=True, alias="vehicle.operator.last_name"
    )
    operator_name = dy.String(metadata={"reader_roles": ["OperatorName"]}, nullable=True, alias="vehicle.operator.name")
    operator_logon_time = dy.UInt64(nullable=True, alias="vehicle.operator.logon_time")
    block_id = dy.String(nullable=True, alias="vehicle.block_id")
    run_id = dy.String(nullable=True, alias="vehicle.run_id")
    stop_id = dy.String(nullable=True, alias="vehicle.stop_id")
    current_stop_sequence = dy.UInt32(nullable=True, alias="vehicle.current_stop_sequence")
    revenue = dy.Bool(nullable=True, alias="vehicle.revenue")
    current_status = dy.String(nullable=True, alias="vehicle.current_status")
    load = dy.UInt16(nullable=True, alias="vehicle.load")
    capacity = dy.UInt16(nullable=True, alias="vehicle.capacity")
    occupancy_percentage = dy.UInt16(nullable=True, alias="vehicle.occupancy_percentage")
    occupancy_status = dy.String(nullable=True, alias="vehicle.occupancy_status")
    state_of_charge_percentage = dy.UInt16(nullable=True, alias="vehicle.state_of_charge_percentage")
    state_of_charge_timestamp = dy.UInt64(nullable=True, alias="vehicle.state_of_charge_timestamp")


class RtBusVehicleDetail(GTFSRTDetail):
    """
    Detail for how to convert RT GTFS Bus Vehicle Positions from json
    entries into parquet tables.
    """

    @property
    def partition_column(self) -> str:
        return "vehicle.trip.route_id"

    @property
    def import_schema(self) -> pyarrow.schema:
        return pyarrow.schema([v.pyarrow_field(k) for k, v in BusLocVehicleRecord.entity.inner.inner.items()])  # type: ignore[attr-defined]

    @property
    def table_sort_order(self) -> List[Tuple[str, str]]:
        return [
            ("vehicle.block_id", "ascending"),
            ("vehicle.vehicle.id", "ascending"),
            ("feed_timestamp", "ascending"),
        ]
