from typing import List, Tuple
import dataframely as dy
import pyarrow

from lamp_py.ingestion.gtfs_rt_detail import GTFSRTDetail, FeedMessage, TripUpdateTable
from lamp_py.ingestion.gtfs_rt_structs import (
    trip_descriptor,
    vehicle_descriptor,
    stop_time_event,
)
from lamp_py.ingestion.utils import explode_table_column, flatten_table_schema


class TripUpdateRecord(FeedMessage):
    """Each TripUpdate message generated by GTFS-RT."""

    entity = dy.List(
        inner=dy.Struct(
            inner={
                "id": dy.String(min_length=1),
                "trip_update": dy.Struct(
                    inner={
                        "trip": trip_descriptor,
                        "vehicle": vehicle_descriptor,
                        "stop_time_update": dy.List(
                            dy.Struct(
                                inner={
                                    "stop_sequence": dy.UInt32(),
                                    "stop_id": dy.String(nullable=True),
                                    "arrival": stop_time_event,
                                    "departure": stop_time_event,
                                    "schedule_relationship": dy.String(nullable=True),
                                    "boarding_status": dy.String(nullable=True),  # MBTA Enhanced Field
                                },
                            ),
                            min_length=1,
                        ),
                        "timestamp": dy.UInt64(nullable=True),
                        "delay": dy.Int32(nullable=True),
                    }
                ),
            }
        ),
        min_length=1,
    )


class ConcentrateTripUpdateTable(TripUpdateTable):
    """Flattened GTFS-RT TripUpdates data with exploded stop_time_update."""

    boarding_status = dy.String(nullable=True, alias="trip_update.stop_time_update.boarding_status")


class RtTripDetail(GTFSRTDetail[ConcentrateTripUpdateTable, TripUpdateRecord]):
    """
    Detail for how to convert RT GTFS Trip Updates from json entries into
    parquet tables.
    """

    @property
    def table_schema(self) -> type[ConcentrateTripUpdateTable]:
        return ConcentrateTripUpdateTable

    @property
    def record_schema(self) -> type[TripUpdateRecord]:
        return TripUpdateRecord

    def transform_for_write(self, table: pyarrow.table) -> pyarrow.table:
        """modify table schema before write to parquet"""
        return flatten_table_schema(explode_table_column(flatten_table_schema(table), "trip_update.stop_time_update"))

    @property
    def partition_column(self) -> str:
        return "id"

    @property
    def import_schema(self) -> pyarrow.schema:
        return pyarrow.schema([v.pyarrow_field(k) for k, v in self.record_schema.entity.inner.inner.items()])  # type: ignore[attr-defined]

    # pylint: disable=R0801
    # Similar lines in 2 files
    @property
    def table_sort_order(self) -> List[Tuple[str, str]]:
        return [
            ("trip_update.trip.route_pattern_id", "ascending"),
            ("trip_update.trip.direction_id", "ascending"),
            ("trip_update.vehicle.id", "ascending"),
        ]

    # pylint: enable=R0801
