from typing import List

import dataframely as dy

from lamp_py.runtime_utils.remote_files import bus_vehicle_positions
from .config_rt_vehicle import RtVehicleTable, VehicleDetail
from .gtfs_rt_structs import FeedEntity, FeedMessage, VehiclePosition, Operator


class BusLocVehiclePosition(VehiclePosition, kw_only=True):
    """Each VehiclePosition message generated by BusLoc."""

    operator: Operator
    location_source: str | None = None
    block_id: str | None = None
    run_id: str | None = None
    revenue: bool | None = None
    load: int | None = None
    capacity: int | None = None
    state_of_charge_percentage: int | None = None
    state_of_charge_timestamp: int | None = None


class BusLocVehiclePositionEntity(FeedEntity, kw_only=True):
    """Each entity in the BusLoc VehiclePositions feed."""

    vehicle: BusLocVehiclePosition


class BusLocVehiclePositionMessage(FeedMessage):
    """A snapshot of the BusLoc VehiclePositions feed."""

    entity: List[BusLocVehiclePositionEntity]


class BusLocVehicleTable(RtVehicleTable):
    """Flattened BusLoc VehiclePositions data."""

    operator_id = dy.String(nullable=True, alias="vehicle.operator.id")
    operator_first_name = dy.String(
        metadata={"reader_roles": ["OperatorName"]}, nullable=True, alias="vehicle.operator.first_name"
    )
    operator_last_name = dy.String(
        metadata={"reader_roles": ["OperatorName"]}, nullable=True, alias="vehicle.operator.last_name"
    )
    operator_name = dy.String(metadata={"reader_roles": ["OperatorName"]}, nullable=True, alias="vehicle.operator.name")
    operator_logon_time = dy.UInt64(nullable=True, alias="vehicle.operator.logon_time")
    load = dy.UInt16(nullable=True, alias="vehicle.load")
    capacity = dy.UInt16(nullable=True, alias="vehicle.capacity")
    state_of_charge_percentage = dy.UInt16(nullable=True, alias="vehicle.state_of_charge_percentage")
    state_of_charge_timestamp = dy.UInt64(nullable=True, alias="vehicle.state_of_charge_timestamp")


class RtBusVehicleDetail(VehicleDetail):
    """How to convert BusLoc Vehicle Positions from structs into a table."""

    record_schema = BusLocVehiclePositionMessage
    table_schema = BusLocVehicleTable
    remote_location = bus_vehicle_positions
