from abc import ABC
from abc import abstractmethod
from typing import Optional, List, Tuple

import dataframely as dy
import pyarrow

from lamp_py.ingestion.utils import flatten_table_schema


class FeedMessage(dy.Schema):
    """GTFS Realtime message containing aheader and entity list: one of TripUpdates, VehiclePositions, or Alerts."""

    header = dy.Struct(
        inner={
            "gtfs_realtime_version": dy.String(),
            "incrementality": dy.String(),
            "timestamp": dy.UInt64(),
        }
    )
    entity = dy.List(inner=dy.Any())


class FeedEntityTable(dy.Schema):
    """Flattened entity list from GTFS Realtime feed messages."""

    id = dy.String(primary_key=True)
    feed_timestamp = dy.UInt64(primary_key=True)


class TripUpdateTable(FeedEntityTable):
    """Base class for pre- and post-Concentrate/Swiftly TripUpdates."""

    # trip_update fields
    trip_update_timestamp = dy.UInt64(nullable=True, alias="trip_update.timestamp")
    trip_update_delay = dy.Int32(nullable=True, alias="trip_update.delay")

    # trip fields
    trip_id = dy.String(nullable=True, alias="trip_update.trip.trip_id")
    route_id = dy.String(nullable=True, alias="trip_update.trip.route_id")
    direction_id = dy.UInt8(nullable=True, alias="trip_update.trip.direction_id")
    trip_start_time = dy.String(nullable=True, alias="trip_update.trip.start_time")
    trip_start_date = dy.String(nullable=True, alias="trip_update.trip.start_date")
    trip_schedule_relationship = dy.String(nullable=True, alias="trip_update.trip.schedule_relationship")
    trip_route_pattern_id = dy.String(nullable=True, alias="trip_update.trip.route_pattern_id")
    trip_revenue = dy.Bool(nullable=True, alias="trip_update.trip.revenue")
    trip_last_trip = dy.Bool(nullable=True, alias="trip_update.trip.last_trip")

    # vehicle fields
    vehicle_id = dy.String(nullable=True, alias="trip_update.vehicle.id")
    vehicle_label = dy.String(nullable=True, alias="trip_update.vehicle.label")
    vehicle_license_plate = dy.String(nullable=True, alias="trip_update.vehicle.license_plate")

    # stop_time_update fields (exploded from list)
    stop_sequence = dy.UInt32(primary_key=True, alias="trip_update.stop_time_update.stop_sequence")
    stop_id = dy.String(nullable=True, alias="trip_update.stop_time_update.stop_id")
    arrival_delay = dy.Int32(nullable=True, alias="trip_update.stop_time_update.arrival.delay")
    arrival_time = dy.Int64(nullable=True, alias="trip_update.stop_time_update.arrival.time")
    arrival_uncertainty = dy.Int32(nullable=True, alias="trip_update.stop_time_update.arrival.uncertainty")
    departure_delay = dy.Int32(nullable=True, alias="trip_update.stop_time_update.departure.delay")
    departure_time = dy.Int64(nullable=True, alias="trip_update.stop_time_update.departure.time")
    departure_uncertainty = dy.Int32(nullable=True, alias="trip_update.stop_time_update.departure.uncertainty")
    stop_schedule_relationship = dy.String(nullable=True, alias="trip_update.stop_time_update.schedule_relationship")


class GTFSRTDetail[T: FeedEntityTable, M: FeedMessage](ABC):
    """
    Abstract Base Class for all GTFSRTDetail implementations.

    GTFSRTDetail classes must implement all methods and properties that are
    defined.
    """

    def transform_for_write(self, table: pyarrow.table) -> pyarrow.table:
        """modify table schema before write to parquet"""
        return flatten_table_schema(table)

    @property
    @abstractmethod
    def table_schema(self) -> type[T]:
        """Schema for the flattened table representation of this GTFS-RT data."""

    @property
    @abstractmethod
    def record_schema(self) -> type[M]:
        """Schema for the raw GTFS-RT record structure."""

    @property
    @abstractmethod
    def partition_column(self) -> str:
        """Column used to partition parquet files for this config"""

    @property
    @abstractmethod
    def import_schema(self) -> pyarrow.schema:
        """Get the import schema for the parquet table generated by this config"""

    @property
    def table_sort_order(self) -> Optional[List[Tuple[str, str]]]:
        """
        Provide list of fields to sort pyarrow table before writing to parquet

        table_sort_order should be configured to optimize parquet file size
        when writing to disk

        Currently specified sort orders were determined by a small amount of experimentation

        TODO: perform additional experiments to optimize sort order of all parquet file types  # pylint: disable=fixme
        """
        return None
