from abc import ABC
from abc import abstractmethod
from typing import Optional, List, Tuple

import dataframely as dy
import pyarrow

from lamp_py.ingestion.utils import flatten_table_schema


class GTFSRTDetail(ABC):
    """
    Abstract Base Class for all GTFSRTDetail implementations.

    GTFSRTDetail classes must implement all methods and properties that are
    defined.
    """

    def transform_for_write(self, table: pyarrow.table) -> pyarrow.table:
        """modify table schema before write to parquet"""
        return flatten_table_schema(table)

    @property
    def table_schema(self) -> Optional[type[dy.Schema]]:
        """Schema for the flattened table representation of this GTFS-RT data."""
        return None

    @property
    def record_schema(self) -> Optional[type["GTFSRealtime"]]:
        """Schema for the raw GTFS-RT record structure."""
        return None

    @property
    @abstractmethod
    def partition_column(self) -> str:
        """Column used to partition parquet files for this config"""

    @property
    @abstractmethod
    def import_schema(self) -> pyarrow.schema:
        """Get the import schema for the parquet table generated by this config"""

    @property
    def table_sort_order(self) -> Optional[List[Tuple[str, str]]]:
        """
        Provide list of fields to sort pyarrow table before writing to parquet

        table_sort_order should be configured to optimize parquet file size
        when writing to disk

        Currently specified sort orders were determined by a small amount of experimentation

        TODO: perform additional experiments to optimize sort order of all parquet file types  # pylint: disable=fixme
        """
        return None


class GTFSRealtime(dy.Schema):
    """Abstract GTFS-RT schema. Each feed message contains a header and a list of entities, which can be either TripUpdates, VehiclePositions, or Alerts."""

    header = dy.Struct(
        inner={
            "gtfs_realtime_version": dy.String(),
            "incrementality": dy.String(),
            "timestamp": dy.UInt64(),
        }
    )
    entity = dy.List(inner=dy.Any())
