name: Lambda Deploy
description: Deploys new Lambda function code
inputs:
  aws-access-key-id:
    description: AWS access key
    required: true
  aws-secret-access-key:
    description: AWS secret key
    required: true
  dry-run:
    description: >-
      If truthy, the deploy will be a dry run, or will not be attempted at all
      if `aws-access-key-id` is blank (instead of erroring)
    required: false
    default: ""
  environment:
    description: Name of the environment to deploy to (dev/prod)
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/poetry_deps
      with:
        poetry-dir: py_gtfs_rt_ingestion

    - name: Create build folder
      working-directory: py_gtfs_rt_ingestion
      run: |
        # build the ingestion modules and install its dependencies to package
        poetry build
        poetry run pip install --upgrade -t package dist/*.whl
        # add the batch and ingest scripts to the package
        cp -v batch_files.py package/batch_files.py
        cp -v ingest.py package/ingest.py
      shell: bash

    - name: Install AWS SSL Cert
      working-directory: py_gtfs_rt_ingestion/
      run: |
        curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -o aws-cert-bundle.pem
        echo "acaf8712f8d71c05f85503c6b90fd0127e95ff0091bf094a22a650119684a08e  aws-cert-bundle.pem" | sha256sum -c -
        cp -v aws-cert-bundle.pem package/aws-cert-bundle.pem
      shell: bash

    - name: Download psycopg2 with SSL and Postgres installed 
      working-directory: .
      run: |
        # taken from https://gitlab.com/psyhomb/aws-psycopg2
        #
        # probably want to roll this ourselves.
        wget https://gitlab.com/psyhomb/aws-psycopg2/-/jobs/2001591421/artifacts/raw/target/psycopg2-2.9.3-python3.9-libpq9.6.24.tar.gz
        tar -xf psycopg2-2.9.3-python3.9-libpq9.6.24.tar.gz
        ls .
        ls psycopg2
      shell: bash

    - name: Install psycopg2 with libpq
      working-directory: py_gtfs_rt_ingestion
      run: |
        # remove psycopg2 and update it with our home built one
        rm -r package/psycopg2
        mv /home/runner/work/lamp/lamp/psycopg2 package/
      shell: bash

    - name: Create zip archive
      working-directory: py_gtfs_rt_ingestion/package
      run: |
        zip -r ../lamp_lambdas.zip . -x '*.pyc'
      shell: bash

    - name: Deploy Ingest Lambda
      working-directory: py_gtfs_rt_ingestion
      run: >-
        aws lambda update-function-code
        --function-name lamp-${{ inputs.environment }}-ingest
        --zip-file fileb://lamp_lambdas.zip
        ${{ inputs.dry-run && '--dry-run' || '' }}
      if: ${{ !inputs.dry-run || inputs.aws-access-key-id }}
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1

    - name: Deploy Batch Lambda
      working-directory: py_gtfs_rt_ingestion
      run: >-
        aws lambda update-function-code
        --function-name lamp-${{ inputs.environment }}-batcher
        --zip-file fileb://lamp_lambdas.zip
        ${{ inputs.dry-run && '--dry-run' || '' }}
      if: ${{ !inputs.dry-run || inputs.aws-access-key-id }}
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1
