"""trips and metrics processing updates

Revision ID: 2e9d81949da8
Revises: c514f5b5e389
Create Date: 2023-04-13 08:41:00.491868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e9d81949da8"
down_revision = "c514f5b5e389"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vehicle_trips",
        "trunk_route_id",
        existing_type=sa.VARCHAR(length=60),
        nullable=True,
    )
    op.alter_column(
        "vehicle_trips",
        "stop_count",
        existing_type=sa.SMALLINT(),
        nullable=True,
    )
    op.add_column(
        "vehicle_trips",
        sa.Column("fk_static_timestamp", sa.Integer(), nullable=True),
    )
    update_timestamp_query = """
        UPDATE 
            vehicle_trips 
        SET 
            fk_static_timestamp = subq.fk_static_timestamp
        FROM 
            (SELECT 
                trip_hash, min(fk_static_timestamp) AS fk_static_timestamp 
            FROM 
                vehicle_events 
            GROUP BY 
                trip_hash
            ) as subq
        WHERE
            subq.trip_hash = vehicle_trips.trip_hash
        ;
    """
    op.execute(update_timestamp_query)
    op.alter_column(
        "vehicle_trips",
        "fk_static_timestamp",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.create_foreign_key(
        "vehicle_trips_fk_static_timestamp_fkey",
        "vehicle_trips",
        "static_feed_info",
        ["fk_static_timestamp"],
        ["timestamp"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "vehicle_trips_fk_static_timestamp_fkey",
        "vehicle_trips",
        type_="foreignkey",
    )
    op.drop_column("vehicle_trips", "fk_static_timestamp")
    op.execute("DELETE FROM vehicle_trips WHERE stop_count IS NULL;")
    op.alter_column(
        "vehicle_trips",
        "stop_count",
        existing_type=sa.SMALLINT(),
        nullable=False,
    )
    op.execute("DELETE FROM vehicle_trips WHERE trunk_route_id IS NULL;")
    op.alter_column(
        "vehicle_trips",
        "trunk_route_id",
        existing_type=sa.VARCHAR(length=60),
        nullable=False,
    )
    # ### end Alembic commands ###
