name: Set up dependencies
description: Loads poetry deps for a CI/CD job, install them if not cached
runs:
  using: composite
  steps:
    - uses: ./.github/actions/tools

    - name: Install Poetry Deps
      working-directory: py_gtfs_rt_ingestion
      run: |
        poetry config virtualenvs.create false
        poetry install
      shell: bash
