name: Setup ASDF Tools
description: Loads ASDF tools for for a CI/CD job, installing them if not cached
outputs:
  cache-hit:
    description: "Whether the ASDF cache was hit"
    value: ${{ steps.asdf-cache.outputs-cache-hit }}
runs:
  using: composite
  steps:
    # cache the ASDF directory, using values from .tool-versions
    - name: ASDF Tools Cache
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
      id: asdf-cache
      with:
        path: ~/.asdf
        # runner.os vs CACHE_UUID secret
        key: ${{ runner.os}}-asdf-${{ hashFiles('**/.tool-versions') }}

    - name: Install ASDF Tools
      uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4
      if: steps.asdf-cache.outputs.cache-hit != 'true'

    - name: Re-shim ASDF Install
      uses: mbta/actions/reshim-asdf@20a677d22e01056a0ea63ff3b996bbc774188770 # v2
