---
title: "Exporting [a lot of] Heavy Rail TripUpdates"
format: html
date: 2026-04-29
author: "crunkel@mbta.com"
---

We struggle to modify our current ingestion process to produce non-uniqued datasets of reasonable size.
In lieu of a production-ready solution, I'll create an export of Heavy Rail---that's `route_id`s `Red`, `Orange`, and `Blue`---TripUpdates for the last 60 days.

Luckily, I have some helpful patterns from my foray into updating our ingestion:

```{python}
import os
from datetime import date
import polars as pl

from lamp_py.ingestion.config_rt_trip import RtTripDetail
from lamp_py.ingestion.converter import ConfigType
from lamp_py.aws.s3 import file_list_from_s3
from lamp_py.runtime_utils.remote_files import LAMP, S3_ARCHIVE
```

To start, let's find the files for today:

```{python}
files = [
    file for file in file_list_from_s3(S3_ARCHIVE, os.path.join(LAMP, "delta", date.today().strftime("%Y/%m/%d")), max_list_size = 1_000_000) if ConfigType.from_filename(file) == ConfigType.RT_TRIP_UPDATES
    ]
```

Each file is named like this (with a different timestamp):

```{python}
files[0]
```

And there are this many files:

```{python}
len(files)
```

Multiply that by 3MB per file and you have a pretty high memory load, even just for today's data.
To reduce the load, I'll stream in the data.
Let's try this with 5 records:

```{python}
(
    RtTripDetail
    .scan_ndjson(files[0:4])
    .collect()
)
```

Great, now we'll add a filter:

```{python}
%%time
(
    RtTripDetail
    .scan_ndjson(files[0:4])
    .filter(pl.col("trip_update.trip.route_id").is_in(["Red", "Blue", "Orange"]))
    .collect()
)
```

My interpeted language brain worries that the filter applied after the unnesting may result in bad performance.
To validate this, I'll check the plan:

```{python}
(
    RtTripDetail
    .scan_ndjson(files[0:4])
    .filter(pl.col("trip_update.trip.route_id").is_in(["Red", "Blue", "Orange"]))
    .explain(optimized = True)
)
```

Sheesh.
Okay, instead of using `RtTripDetail.scan_ndjson` directly, I'll imitate it and add in the filter:

```{python}
from lamp_py.utils.typing import struct_to_schema
(
    pl.scan_ndjson(files[0:4])
    .match_to_schema(
                struct_to_schema(RtTripDetail.record_schema).to_polars_schema(),
                missing_columns="insert",
                missing_struct_fields="insert",
                extra_columns="ignore",
                extra_struct_fields="ignore",
                integer_cast="upcast",
                float_cast="upcast",
            )
    .select("entity", pl.col("header").struct.field("timestamp").alias("feed_timestamp"))
    .explode("entity")
    .filter(
        pl.col("entity").struct.field("trip_update")
        .struct.field("trip")
        .struct.field("route_id").is_in(
            ["Red", "Blue", "Orange"]
        )
    )
    .unnest("entity")
    .unnest(separator=".")
    .unnest(separator=".")
    .explain(optimized = True)
)
```

Better plan, let's see if it results in less time:

```{python}
%%time
(
    pl.scan_ndjson(files[0:4])
    .match_to_schema(
                struct_to_schema(RtTripDetail.record_schema).to_polars_schema(),
                missing_columns="insert",
                missing_struct_fields="insert",
                extra_columns="ignore",
                extra_struct_fields="ignore",
                integer_cast="upcast",
                float_cast="upcast",
            )
    .select("entity", pl.col("header").struct.field("timestamp").alias("feed_timestamp"))
    .explode("entity")
    .filter(
        pl.col("entity").struct.field("trip_update")
        .struct.field("trip")
        .struct.field("route_id").is_in(
            ["Red", "Blue", "Orange"]
        )
    )
    .unnest("entity")
    .unnest(separator=".")
    .unnest(separator=".")
    .collect()
)
```

It doesn't!
Okay, scratch that, we'll use it directly.
I guess reaching into a struct incurs some overhead.

Okay, now, let's try to write today's data to a file:

```{python}
%%time
(
    RtTripDetail
    .scan_ndjson(files)
    .sink_parquet("/tmp/today.parquet")
)
```

And what kind of data did this result in?

```{python}
pl.scan_parquet("/tmp/today.parquet").head(10).collect()
```

Ah---we send to Tableau, we'll actually need to do some more transformations.
Luckily, we can just tap more existing code:

```{python}
from lamp_py.tableau.conversions.convert_gtfs_rt_trip_updates import restrict_tu_to_only_terminal_stop_ids, apply_timezone_conversions, append_prediction_valid_duration
from lamp_py.utils.filter_bank import HeavyRailFilter
```

So, our code above becomes:

```{python}
%%time
(
    RtTripDetail
    .scan_ndjson(files)
    .filter(pl.col("trip_update.trip.route_id").is_in(["Red", "Orange", "Blue"]))
    .explode("trip_update.stop_time_update")
    .unnest(separator = ".")
    .filter(pl.col("trip_update.stop_time_update.stop_id").is_in(HeavyRailFilter.terminal_stop_ids))
    .unnest(separator = ".")
    .filter(pl.col("trip_update.stop_time_update.departure.time").is_not_null())
    .with_columns(pl.selectors.by_dtype(pl.UInt64).cast(pl.Datetime).dt.convert_time_zone("America/New_York"))
    .sink_parquet("/tmp/today.parquet")
)
```

Now we have:

```{python}
pl.scan_parquet("/tmp/today.parquet").head(10).collect()
```

With a size of

```{python}
from pyarrow.parquet import read_metadata
read_metadata("/tmp/today.parquet")
```

Not bad in terms of size!
Still, I'd like to do this in batches for error handling.
The issue is that appending to a Parquet file isn't really possible.
Instead, I'm going to sink to a delta file (which is, itself, a directory of Parquet files).

```{python}
thirty_days = [
    file for d in pl.date_range(date(2026, 3, 29), date(2026, 4, 28), eager = True).to_list()
    for file in file_list_from_s3(S3_ARCHIVE, os.path.join(LAMP, "delta", d.strftime("%Y/%m/%d")), max_list_size = 1_000_000)
    if ConfigType.from_filename(file) == ConfigType.RT_TRIP_UPDATES
    ]
```

Since this list takes so long to compile, I'll write it to disk so that I can re-trace my steps easily:

```{python}
from json import dumps
with open("/tmp/thirty_day_files.json", mode = "wt") as f:
    f.write(dumps(thirty_days))
```

Then call the files back:

```{python}
from json import load
with open("/tmp/thirty_day_files.json") as f:
    thirty_days = load(f)
```

To speed all this up, we should use pyarrow's filesystem and write these to files:

```{python}
%%time
for d in pl.date_range(date(2026, 3, 14), date(2026, 3, 28), eager = True).to_list():
    files = [
        file for file in
        file_list_from_s3(S3_ARCHIVE, os.path.join(LAMP, "delta", d.strftime("%Y/%m/%d")), max_list_size = 1_000_000)
        if ConfigType.from_filename(file) == ConfigType.RT_TRIP_UPDATES
    ]

    (
        RtTripDetail
        .scan_ndjson(files)
        .filter(pl.col("trip_update.trip.route_id").is_in(["Red", "Orange", "Blue"]))
        .explode("trip_update.stop_time_update")
        .unnest(separator = ".")
        .filter(pl.col("trip_update.stop_time_update.stop_id").is_in(HeavyRailFilter.terminal_stop_ids))
        .unnest(separator = ".")
        .filter(pl.col("trip_update.stop_time_update.departure.time").is_not_null())
        .with_columns(pl.selectors.by_dtype(pl.UInt64).cast(pl.Datetime).dt.convert_time_zone("America/New_York"))
        .sink_parquet(os.path.join("/tmp", "sixty_days", f"date={d.isoformat()}", "0.parquet"))
    )
    print("Wrote ", str(d))
```
