name: Set up dependencies
description: Loads poetry dependencies for a CI/CD job, install them if not cached

runs:
  using: composite
  steps:
    - name: ASDF Install 
      uses: ./.github/actions/tools

    - name: Poetry Cache
      uses: actions/cache@v3
      id: poetry-cache
      with:
        path: | 
          ~/.cache/pypoetry
          **/python_src/.venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Poetry Install
      working-directory: python_src
      # env use python3.9 to force usage of python3.9 installed by asdf over system python version
      run: |
        poetry env use python3.9
        poetry install -v 
      shell: bash
      if: "!steps.poetry-cache.outputs.cache-hit"
