name: Move Asana Ticket after PR Merged
on:
  pull_request:
    types: [closed]

jobs:
  move-asana-ticket-to_done_job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Github-Asana Move Ticket Action
        uses: mbta/github-asana-action@v4.3.0
        with:
          asana-pat: ${{ secrets.ASANA_SECRET_FOR_MOVE_ACTION }}
          trigger-phrase: "Asana Task:"
          target-section: "Done"
          mark-complete: true

  move-asana-ticket-to_todo_job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    steps:
      - name: Github-Asana Move Ticket Action
        uses: mbta/github-asana-action@v4.3.0
        with:
          asana-pat: ${{ secrets.ASANA_SECRET_FOR_MOVE_ACTION }}
          trigger-phrase: "Asana Task:"
          target-section: "To Do"
