name: Validate YAML

on:
  push:
    branches:
      - main
    paths:
      - "**.yaml"
  pull_request:
    paths:
      - "**.yaml"

permissions:
  contents: read

jobs:
  build:
    name: Validate YAML actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - run: yamllint . -f parsable --strict
      - name: Run Zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e  # v0.5.3
        with:
          advanced-security: false
          persona: regular
          inputs: .github
