name: Validate YAML

on:
  push:
    branches:
      - main
    paths:
      - "**.yaml"
  pull_request:
    paths:
      - "**.yaml"

permissions:
  contents: read

jobs:
  build:
    name: Validate YAML actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          persist-credentials: false
      - run: yamllint . -f parsable --strict
      - uses: mbta/actions/zizmor@797bb12aca2b8dbc58195b6b463ed52814118cf0
        with:
          minimum_issue_severity: medium