name: Deploy to Staging

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  contents: read

jobs:
  python-ci:
    uses: ./.github/workflows/ci_python.yaml
    permissions:
      contents: read
      pull-requests: write
  deploy:
    name: Deploy to Staging
    needs: python-ci
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: staging
    uses: ./.github/workflows/deploy-base.yaml
    with:
      environment: staging
      deploy-ingestion: true
      deploy-rail-pm: true
      deploy-bus-pm: true
      deploy-tm-ingestion: true
      deploy-tableau-publisher: true
      deploy-flashback: true
      deploy-lightswitch: true
    secrets:
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  run-lightswitch:
    needs: deploy
    uses: ./.github/workflows/run-task.yaml
    with:
      environment: staging
      task: Lightswitch
    permissions:
      contents: read
      id-token: write
