name: Continuous Integration (Elixir)

on:
  push:
    branches: main
    paths:
      - 'api/**'
      - '.github/workflows/elixir.yaml'
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/elixir.yaml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Elixir Setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Elixir Deps
        uses: ./.github/actions/elixir_deps

  dev:
    name: Dev Tasks
    runs-on: ubuntu-22.04
    needs: setup

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Elixir Deps
        uses: ./.github/actions/elixir_deps

      - name: Restore dev build cache
        id: dev-tasks
        uses: actions/cache@v3
        with:
          path: api/_build/dev
          key: ${{ runner.os }}-mix-dev-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-dev-

      - name: Compile (warnings as errors)
        run: mix compile --force --warnings-as-errors
        working-directory: api
        if: steps.dev-tasks.outputs.cache-hit != 'true'

      - name: Check formatting
        run: mix format --check-formatted
        working-directory: api
        if: steps.dev-tasks.outputs.cache-hit != 'true'

  test:
    name: Test Tasks
    runs-on: ubuntu-22.04
    needs: setup

    services:
      postgres:
        image: postgres:14.4
        ports:
          - 5432:5432
        env:
          # matches api/config/test.exs
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: performance_manager_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Elixir Deps
        uses: ./.github/actions/elixir_deps

      - name: Setup Python
        uses: ./.github/actions/poetry_deps

      - name: Run tests
        run: mix test
        working-directory: api
