name: Deploy Performance Manager to Dev

on:
  workflow_run:
    workflows: ["Performance Manager CI"]
    types: [completed]
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@main
    with:
      app-name: lamp-performance-manager
      environment: dev
      dockerfile-path: ./performance_manager/
      cluster: lamp
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
