name: Run Task

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        options:
          - dev
          - staging
          - prod
      task:
        description: Task
        type: choice
        options:
          - Tableau Publisher
          - Transit Master Ingestion
          - Lightswitch
      ref:
        description: Branch, Commit, or Tag
        type: string
        required: true
        default: main
  workflow_call:
    inputs:
      environment:
        type: string
      task:
        type: string
      ref:
        type: string
        required: false
        default: main
    secrets:
      AWS_ROLE_ARN:
        required: true

concurrency:
  group: run-task-${{ inputs.environment }}-${{ inputs.task }}
  cancel-in-progress: true

jobs:
  run_task:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Branch
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          ref: ${{ inputs.branch }}
          persist-credentials: false

      - name: Generate Task Name
        run: |
          if [ "${INPUTS_TASK}" == "Tableau Publisher" ]; then
            echo "task_name=tableau-publisher" >> $GITHUB_ENV
          elif [ "${INPUTS_TASK}" == "Transit Master Ingestion" ]; then
            echo "task_name=tm-ingestion" >> $GITHUB_ENV
          elif [ "${INPUTS_TASK}" == "Lightswitch" ]; then
            echo "task_name=lightswitch" >> $GITHUB_ENV
          fi
        env:
          INPUTS_TASK: ${{ inputs.task }}
      - name: Run Task Action
        uses: ./.github/actions/run_task
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          cluster: 'lamp'
          service: lamp-${{ env.task_name }}-${{ inputs.environment }}
